# Generated by Django 4.2.1 on 2023-09-05 11:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tullys', '0002_shift'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shift',
            name='day',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)]),
        ),
    ]
