# Generated by Django 4.2.1 on 2023-09-05 11:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tullys', '0003_alter_shift_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shift',
            name='finish_time',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(24)]),
        ),
        migrations.AlterField(
            model_name='shift',
            name='start_time',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(24)]),
        ),
    ]
