# Generated by Django 4.2.1 on 2024-02-22 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tullys', '0004_alter_shift_finish_time_alter_shift_start_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('files', models.FileField(upload_to='files')),
            ],
        ),
    ]
